stages:
  - build

variables:
  DOCKER_IMAGE: $CI_REGISTRY/landing-app:latest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - pwd
    - docker build -t $DOCKER_IMAGE .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE