name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image (Prod)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: benmotevalli/test-release-pipeline-prod:latest
          push: true

  build-and-push-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

      - name: Build and Push Docker image (Dev)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.dev
          tags: benmotevalli/test-release-pipeline-dev:${{ steps.timestamp.outputs.timestamp }}
          push: true
